pipData <- read.csv("./PiPResults.csv")
persData <- read.csv("./PersResults.csv")
resultsFile <- "results.txt"
sink("results.txt")
source("corrAny.R")
source("attYN.R")
source("teacher.R")
source("present.R")
source("present2.R")
source("teacher2.R")
source("crossFactor.R")
source("sexStemOnl.R")
source("codedResponses.R")
source("polr.R")
source("expertise.R")
sink()
sink()